spring:
  application:
    name: spring-boot-admin-sample-war
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          service-base-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS